name: cs361
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - ipykernel
  - jupyterlab
  - seaborn
  - nodejs
  - rise
  - pip:
    - jupyter-contrib-nbextensions
    - ipykernel
    - ipympl
    - ipython
    - ipywidgets
    - jupyter
    - matplotlib
    - numpy
    - scikit-learn
    - river

